### ISSUE TITLE
Can you update the bot with this x= y=?

### ISSUE THREAD

**Issue by Komischerboy** [tiehm/iloveradio-bot#1]
Can you update the bot? ILoveRadio changed the URL to: 
iloveradio.de/typo3conf/ext/ep_channel/Scripts/voting.php?r=43833&tx_epvoting_voting_vote[vote]=22&tx_epvoting_voting_vote[math]=plus&tx_epvoting_voting_vote[uniqueid]=365031847533&x=835&y=231

But I don't know what the x= and y= mean

**Comment by tiehm** [comment]
After a bit of reverse engineering (which wasn't hard at all since their code is not minified or anything similar) it seems that those are the screen coordinates. I haven't looked into this project since quite a bit of time and have to do some test if they actually check the coordinates for anything useful. 
In general you could easily give any good coordinates which would be normal on a normal screen. In testing myself (my browser) I got things like 
```
x=843&y=706
x=855&y=577
x=374&y=677
```

So I will either do a random number generator for these ranges or similar. You are welcome to do this and open a PR.

**Comment by Komischerboy** [comment]
Okay thanks

**Comment by Komischerboy** [comment]
I write a random generator but it doesn't work :c

**Comment by tiehm** [comment]
Mind showing it ?

**Comment by Komischerboy** [comment]
I made it in java

**Comment by tiehm** [comment]
Then I cannot help you with this. I would suggest you to just take some values which I showed above and just change the value by 1 - 20 or so.

**Comment by Komischerboy** [comment]
okay but can you also update your project? Because then its complete

**Comment by tiehm** [comment]
Once I have the time for it, or maybe tomorrow, I will take a look.

**Comment by Komischerboy** [comment]
okay

**Comment by tiehm** [comment]
@Komischerboy I updated the code and it should work now. Tested it myself with 2 proxies and it worked.

**Comment by Komischerboy** [comment]
don't work for me :/ I try to fix it myself

**Comment by Komischerboy** [comment]
ok i fixed it thanks
